@startuml

title Enable Candidate - Sequence Diagram

autonumber
actor Operator as ADM
participant "EnableCandidateUI" as UI <<ui>>
participant ":EnableCandidateController" as CTRL <<application>>
participant ":CandidateManagementService" as CMS <<Service>>
participant "AuthorizationService" as AS <<Service>>
participant "CandidateRepository" as REPO <<repository>>
participant "Candidate" as EU <<domain>>
participant "SystemUser" as SYS <<domain>>

activate ADM
ADM-> UI : Request to enable a candidate
activate UI
UI -> CTRL** : create
UI --> UI: listDisabledCandidates()
UI-> CTRL :disabledCandidates()
activate CTRL
CTRL-->CMS: allCandidate()
activate CMS
CMS->AS: ensureAuthenticatedUserHasAnyOf(BaseRoles.POWER_USER, BaseRoles.ADMIN, BaseRoles.OPERATOR, BaseRoles.CUSTOMER_MANAGER)
activate AS
AS-->CMS: ensures the user has the required role
deactivate AS
CMS->REPO: findAllCandidates()
activate REPO
REPO-->CMS: all candidates
deactivate REPO
CMS-->CTRL: all candidates
deactivate CMS
CTRL-->UI: all candidates
deactivate CTRL
UI-->UI: printCandidates(candidates)
UI-->ADM: returns a list of the disabled candidates
deactivate UI
ADM -> UI : selects a disabled candidate
activate UI
UI -> CTRL : enableCandidate(email)
activate CTRL
CTRL->CMS:enableCandidate(email)
activate CMS
CMS->AS:ensureAuthenticatedUserHasAnyOf(BaseRoles.OPERATOR, BaseRoles.ADMIN)
activate AS
AS--> CMS: ensures the user has operator role
deactivate AS
CMS->REPO: findAll()
activate REPO
REPO-->CMS: finds all candidates
deactivate REPO
CMS->EU:.user()
activate EU
EU->SYS:.activate()
activate SYS
SYS-->EU: candidate activated
deactivate SYS
EU-->CMS: candidate activated
deactivate EU
CMS->REPO:.save(candidate)
activate REPO
REPO-->CMS: candidate enabled
deactivate REPO
CMS-->CTRL: candidate enabled
deactivate CMS
CTRL-->UI: candidate enabled
deactivate CTRL
UI-->ADM: candidate enabled and success message


@enduml
