@startuml
'https://plantuml.com/sequence-diagram

@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Register User to Back Office

autonumber

actor "Admin" as User
participant "AddUserUI" as UI <<UI>>
participant "AddUserController" as Controller <<Application>>
participant "UserService" as UserService <<Service>>
participant "UserRepository" as UserRepository <<Persistence>>

activate User

    User -> UI : Asks to register user
    activate UI

    UI -> Controller** : create

    UI --> User : requests data (username,password, first name, last name, email, role)
    deactivate UI

    User -> UI : Provides data
    activate UI

    UI -> Controller : addUser(username,password, first name, last name, email, role)
    activate Controller

    Controller -> Controller: addUser(username,password, firstName, lastName, email, role, currentTime)
    activate Controller

    Controller -> UserService : registerNewUser(username,password, firstName, lastName, email, role, currentTime)
    activate UserService

    UserService -> UserRepository : save(user)
    activate UserRepository

    UserRepository --> UserService : user
    deactivate UserRepository

    UserService --> Controller : user
    deactivate UserService

    Controller --> Controller : user
    deactivate Controller

    Controller --> UI : user
    deactivate Controller



    UI --> User : Confirms registration
    deactivate UI






@enduml