@startuml
title System Sequence Diagram (US 2004 - As Operator, I want to upload a text file with the data fields (requirements) of a candidate for its verification)

actor Operator as Operator
participant System as "System"

activate Operator
Operator -> System: Request to upload a text file with the requirements of a candidate
activate System
System --> Operator: Retrieves list of all candidates and asks to choose one
deactivate System
Operator -> System: Selects the candidate
activate System
System --> Operator: Retrieves list of all applications of the chosen candidate and asks to choose one
deactivate System
Operator->System: Selects the application
activate System
System --> Operator: Asks to enter the path of the file
deactivate System
Operator->System: Enters the path of the file
activate System
System --> Operator: Confirms the file upload
deactivate System
@enduml