@startuml
autonumber

title "Sequence diagram - 2004 (Upload a text file with the requirements of a candidate for its validation)"
actor Operator as Operator
participant UploadTextFileUI as UI <<UI>>
participant "UploadTextFileController" as CTRL <<application>>
participant "Candidate" as C <<Domain>>
participant "AuthorizationService" as AS <<Service>>
participant "CandidateManagementService" as CMS <<Service>>
participant "CandidateRepository" as CREPO <<Repository>>
participant "JobOpeningApplicationService" as JOAS <<Service>>
participant "JobOpeningApplication" as JOA <<Domain>>
participant "JobOpeningApplicationRepository" as JOREPO <<Repository>>
activate Operator
Operator -> UI: Request to upload a text file with the requirements of a candidate
activate UI
UI-> CTRL**: create
UI->CTRL:allCandidates()
activate CTRL
CTRL->AS:ensureAuthenticatedUserHasAnyOf(BaseRoles.OPERATOR, BaseRoles.ADMIN, BaseRoles.POWERUSER)
activate AS
AS--> CTRL: ensures the user has operator role
deactivate AS
CTRL->CMS:allCandidate()
activate CMS
CMS-> CREPO:findAllCandidates()
activate CREPO
CREPO--> CMS:list of all candidates
deactivate CREPO
CMS-->CTRL : list of all candidates
deactivate CMS
CTRL--> UI: list of all candidates
deactivate CTRL
UI-->UI:printNumeratedList(message, collection)
UI --> Operator: Retrieves list of all candidates and asks to choose one
deactivate UI
Operator -> UI: Selects the candidate
activate UI
UI->C: get(option-1)
activate C
C--> UI: gets the chosen candidate (c)
deactivate C
UI->CTRL:getAppByCandidate(c)
activate CTRL
CTRL->JOAS :getApplicationsByCandidate(c)
activate JOAS
JOAS->JOREPO:allApplicationsByCandidate(c)
activate JOREPO
JOREPO-->JOAS: list of applications
deactivate JOREPO
JOAS-->CTRL: list of applications
deactivate JOAS
CTRL--> UI: list of applications
deactivate CTRL
UI-->UI:printNumeratedListApp(message, collection)
UI--> Operator: Retrieves list of all applications of the chosen candidate and asks to choose one
Operator->UI: Selects the application
UI-> JOA: get(optionApp - 1)
activate JOA
JOA --> UI: gets the chosen application (app)
deactivate JOA
UI-->Operator: Asks to enter the path of the file
Operator-> UI: Enters the path of the file
UI->CTRL:uploadFile(app, path)
activate CTRL
CTRL->AS : ensureAuthenticatedUserHasAnyOf(BaseRoles.OPERATOR, BaseRoles.ADMIN, BaseRoles.POWERUSER)
activate AS
AS-->CTRL: ensures the user has operator role
deactivate AS
CTRL-->JOAS:passGrammar(path)
activate JOAS
JOAS-->CTRL: checks the grammar of the file
deactivate JOAS
CTRL-> JOA:setCandidateRequirements(fileName)
activate JOA
JOA-->CTRL: sets the candidate requirements
deactivate JOA
CTRL-> JOREPO:.save(app)
activate JOREPO
JOREPO-->CTRL: saves the application file in the database
deactivate JOREPO
CTRL-->UI : Confirms the file upload
deactivate CTRL
UI --> Operator: Confirms the file upload
deactivate UI

@enduml


