@startuml




package ui {
        class UploadTextFileUI {
            +printNumeratedList()
            +printNumeratedListApp()
        }
    }




    package application {
        class UploadTextFileController {
            +allCandidates()
            +uploadFile()
            +getApplicationsByCandidate()
            +passGrammar()
        }
    }

    package repository {

        interface CandidateRepository{
            +findAllCandidates()
        }

        interface JobOpeningApplicationRepository{
            +allApplicationsByCandidate()
            +save()
        }
    }

    package domain {

        class AuthorizationService {
            +authorizationService() : AuthorizationService
            +ensureAuthenticatedUserHasAnyOf()
        }
        class JobOpeningApplication{
            +setCandidateRequirements()
        }

        class CandidateManagementService{
            +allCandidate()
        }

        class Candidate {
        }
    }

UploadTextFileUI--> UploadTextFileController
UploadTextFileUI --> Candidate
UploadTextFileController --> AuthorizationService
UploadTextFileController --> CandidateManagementService
UploadTextFileController --> JobOpeningApplicationRepository
UploadTextFileController --> JobOpeningApplication
CandidateManagementService --> CandidateRepository
CandidateRepository --> Candidate
JobOpeningApplicationRepository --> JobOpeningApplication

@enduml