@startuml
'https://plantuml.com/class-diagram

hide methods

rectangle "Job Opening" #bbccaa {

    class JobOpening<<Aggregate Root>><<Entity>>{}

    class JobReference<<Identity>><<Value Object>>{}

    class TitleOrFunction<<Value Object>>{}

    enum ContractType<<Enumerated>><<Value Object>>{
        FULL_TIME
        PART_TIME
    }

    enum Mode<<Enumerated>><<Value Object>>{
        REMOTE
        ON-SITE
        HYBRID
        }


    class VacanciesNumber<<Value Object>>{}

    class Description<<Value Object>>{}

}


rectangle "Job Opening Application" #aaccbb {

    class Application<<Aggregate Root>><<Entity>>{}

    class ApplicationId<<Identity>><<Value Object>>{}

    class AttachedEmail<<Value Object>>{}

    class AttachedFile<<Value Object>>{}

    class ApplicatorData<<Value Object>>{}

    class ApplicationStatus<<Value Object>>{}

    class ApplicationRank<<Value Object>>{}

}


rectangle candidate #aabbcc{
    class Candidate<<Aggregate Root>><<Entity>>{}
    class CandidateId<<Identity>><<Value Object>>{}
    class CurriculumVitae<<Value Object>>{}
}



rectangle "Job Opening Process" #ccbbcc{
    class JobOpeningProcess<<Aggregate Root>><<Entity>>{}
    class JobOpeningProcessId<<Identity>><<Value Object>>{}
'    class JobOpeningProcessStatus<<Value Object>>{}
'    class JobOpeningProcessStage<<Value Object>>{}
    class Phase<<Entity>>{
        }
    enum PhaseType<<Enumerated>><<Value Object>>{
        APPLICATION
        SCREENING
        INTERVIEWS
        ANALYSIS
        RESULT
    }
}

rectangle "Job Opening Interview" #ccbbaa {
    class JobInterview <<Aggregate Root>><<Entity>>{}
    class JobInterviewId<<Identity>><<Value Object>>{}
    class InterviewDate<<Value Object>>{}
    class InterviewTime<<Value Object>>{}
    class Score<<Value Object>>{}
    class InterviewResult<<Value Object>>{}
}



rectangle "Shared Objects" {

    class Email <<Value Object>>
    class Username <<Value Object>>
    class Address <<Value Object>>
    class Name<<Value Object>>{}

}



rectangle "User" #ccbbcc {
    class SystemUser <<Aggregate Root>><<Entity>>{}
    class Password<<Value Object>>{}
    class BaseRole<<Value Object>>{}

    SystemUser "1" --> "1" Email: has
    SystemUser "1" --> "1" Username: has
    SystemUser "1" -up> "1" Password
    SystemUser "1" --> "1" Name
    SystemUser "1" -> "1" BaseRole
    Candidate "1" --|> "1" SystemUser
    JobOpening "1" --> "1" Address

}


JobInterview "1" -up-> "1" JobInterviewId
JobInterview "1" -up-> "1" InterviewDate
JobInterview "1" --> "1" InterviewTime
JobInterview "1" -> "1" Score
JobInterview "1" --> "1" InterviewResult

Application "1" -up-> "1" JobInterview




JobReference "1" <-up- "1" JobOpening
TitleOrFunction "1" <-up- "1" JobOpening
ContractType "1" <-- "1" JobOpening
Mode "1" <-- "1" JobOpening
Description "1" <-up- "1" JobOpening
VacanciesNumber "1" <-up- "1" JobOpening

Candidate "1"--> "1" CandidateId
Candidate "1"--> "1" CurriculumVitae


Application "1" --> "1" ApplicationId
Application "1" --> "1" AttachedEmail
Application "1" --> "1" AttachedFile
Application "1" --> "1" ApplicatorData
Application "*" -----> "1" JobOpening : submitted for
Application "1" -> "1" Candidate : submitted by
Application "1" --> "1" ApplicationStatus
Application "1" --> "0..1" ApplicationRank


JobOpeningProcess "1" -left-> "1" JobOpeningProcessId
JobOpening "1" -----> "*" JobOpeningProcess : has
JobOpeningProcess "1" --> "1" Phase
Phase "1" --> "1" PhaseType

@enduml