@startuml

title Disable User Sequence Diagram

autonumber
actor Administrator as ADM
participant "DisableUserUI" as UI <<ui>>
participant ":DisableUserController" as CTRL <<application>>
participant ":ListUsersUI" as LUI <<ui>>
participant "SystemUser" as User <<domain>>
participant "SystemUserRepository" as REPO <<repository>>


-> UI : onLoad
activate UI
UI -> CTRL : create(userRepo)
UI -> LUI: listEnabledUsers()
activate LUI
LUI --> ADM : displays the \nlist of users
deactivate LUI
ADM -> UI : selects a user
UI -> CTRL : disableUser(user)
activate CTRL
CTRL -> User : disable()
CTRL -> REPO : save(user)
CTRL --> UI : returns success
deactivate CTRL
UI --> ADM : displays success
deactivate UI


@enduml
