@startuml

package UI{
    class AddJobApplicationUI{
    }
}

package Controller{
    class AddJobApplicationController{
    +addJobOpeningApplication()
    +listJobOpenings()
    +readFile()

    }
}
package JobOpening{
package Domain{
 class JobReference{
 }


    class JobOpeningApplication{
    +readFile()
    }
}

package Repository{
    class JobOpeningRepository{
    +getLastIdFromCompany()
    +listJobOpenings()
    }
}

AddJobApplicationUI -> AddJobApplicationController

AddJobApplicationController -> JobOpeningApplication

JobOpeningApplication -> JobOpeningRepository

JobOpeningApplication -> JobReference

@enduml