@startuml

title Register Teacher Sequence Diagram

autonumber
actor CustomerManager as ADM
participant "RegisterCostumerManagerUI" as UI <<ui>>
participant "RegisterCostumerManagerController" as CTRL <<application>>
participant "Jobs4UBuilderFactory" as FAC <<factory>>
participant "CostumerManagerBuilder" as BLD <<builder>>
participant "SystemUser" as SU <<f_entity>>
participant "Jobs4UUser" as J4UU <<domain>>
database "Jobs4UUserRepository" as REPO <<repository>>


-> UI : onLoad
activate UI
UI -> CTRL : create(userRepo, userBuilderFactory)
UI --> ADM : asks input of\n costumer manager details
ADM -> UI : inputs costumer manager details
UI -> CTRL : registerCostumerManager(username, pwd,\n firstName, lastName, email)
activate CTRL
CTRL -> FAC : createJobs4UUserBuilder(role)
activate FAC
FAC -> BLD : create
FAC --> CTRL : builder
deactivate FAC
CTRL -> SU : create
CTRL -> BLD : withSystemUser(sysUser)
CTRL -> BLD : build()
activate BLD
BLD -> J4UU : create(sysUser)
BLD --> CTRL : user
deactivate BLD
CTRL -> REPO : save(user)
CTRL --> UI : returns success
deactivate CTRL
UI --> ADM : displays success




@enduml
