@startuml
title System Sequence Diagram (US 2000a - Register a candidate and create a corresponding user)

actor Operator as Operator
participant System as "System"

activate Operator
Operator -> System: Request to register candidate
activate System
System --> Operator: Receive request to register candidate
deactivate System
Operator -> System: Create candidate record
activate System
System --> Operator: Record created
deactivate System
Operator -> System: Candidate registered successfully
activate System
System --> Operator: Confirmation of candidate registration
deactivate System
Operator -> System: Request to create user for candidate
activate System
System --> Operator: Receive request to create user
deactivate System
Operator -> System: Create user record
activate System
System --> Operator: User record created
deactivate System
Operator -> System: User created
activate System
System --> Operator: Confirmation of user creation
deactivate System

@enduml