@startuml

title US 1006 - List All Data Of Candidate

actor User as U
participant "ListAllDataOfCandidateUI" as UI <<UI>>
participant "ListAllDataOfCandidateController" as C <<Application>>
participant "AuthorizationService" as A <<Service>>
participant "PersistenceContext" as P <<Service>>
participant "RepositoryFactory" as RF <<Persistence>>
participant "CandidateRepository" as CR <<Persistence>>
activate U
U -> UI: Request to list all data of candidate
activate UI
UI -> C: new ListAllDataOfCandidateController()
activate C
C -> A:authorizationService()
A --> C: return AuthorizationService instance
activate A
C ->A : instance.ensureAuthenticatedUserHasAnyOf(BaseRoles.CUSTOMER_MANAGER, BaseRoles.POWER_USER, BaseRoles.ADMIN);
alt User is not authorized
A --> C: throw AuthorizationException
end
alt User is authorized
A --> C: return true
end
deactivate A
C --> UI: return ListAllDataOfCandidateController instance
deactivate C
UI -> C : allCandidates()
activate C
C -> P: repositories()
activate P
P --> C: return repositories
deactivate P
C -> RF: candidateRepository()
activate RF
RF --> C: return candidateRepository
deactivate RF
C -> CR: findAllCandidates()
activate CR
CR --> C: return Iterable<Candidate>
deactivate CR
C --> UI: return Iterable<Candidate>
deactivate C
UI --> U: Display Candidates Id's (emails) list and asks to choose one
deactivate UI
U->UI: Inputs index of candidate
activate UI
UI -> C: candidates.get(index)
activate C
C --> UI: return Candidate
deactivate C
UI --> U: Display Candidate data and returns to Customer Manager Menu


@enduml