@startuml

title Register User Sequence Diagram - Starting point

autonumber
actor Administrator as ADM
participant "AddUserUI" as UI <<ui>>
participant "AddUserController" as ARC <<application>>
participant "SystemUserRepository" as REPO <<repository>>
participant "BaseRoles" as J4UR <<domain>>
participant "UserBuilderFactory" as FAC <<factory>>
participant ":UserBuilder" as BLD <<builder>>
participant ":SystemUser" as SU <<f_entity>>
participant "SystemUserRepository" as REPO <<repository>>
participant ":SystemUser" as SUD <<domain>>


-> UI : onLoad
activate UI
UI -> ARC : create
activate ARC

UI --> ADM : asks input of\n user details
ADM -> UI : inputs user details

UI --> ADM : displays success

ADM --> UI : chooses role

UI -> ARC : getRoleTypes()
ARC -> J4UR : getRoleTypes()
activate J4UR
J4UR --> ARC : roles
deactivate J4UR
ARC --> UI : roles
UI -> ARC : User(username, pwd,\n firstName, lastName, email)

ARC -> FAC : createUserBuilder(role)
activate FAC
FAC -> BLD : create

FAC --> ARC : builder
deactivate FAC

ARC -> SU : create
ARC -> BLD : build()
activate BLD
BLD -> SUD : create(sysUser, birthdate, taxNumber, newNumber, state)
BLD --> ARC : user
deactivate BLD
ARC -> REPO : save(user)
deactivate BLD
ARC --> UI : returns success

deactivate ARC

UI -> ADM : displays success/\nfailure of the operation

deactivate UI





@enduml
