@startuml

actor CustomerManager as CM
participant CandidateManagementService as UI <<UI>>
participant UpdateInterviewAnswerController as CTRL <<Application>>
participant CandidateManagementService as S <<Service>>
participant "PersistenceContext" as P <<Service>>

participant "RepositoryFactory" as RF <<Persistence>>
participant "CandidateRepository" as CR <<Persistence>>
participant "JobOpeningApplicationRepository" as JAR <<Persistence>>

participant ApplicationService as APPS <<Service>>
participant Applications as Aps <<Domain>>




activate CM
CM -> UI: Requests to Upload Interview Answers File
activate UI
UI->CTRL:allCandidate
activate CTRL
CTRL -> S : allCandidate()
activate S
S -> P: repositories()
activate P
P --> S: repositories
deactivate P
S -> RF: candidateRepository()
activate RF
RF --> S: candidateRepository
deactivate RF
S -> CR: findAllCandidates()
activate CR
CR --> S: Candidates

deactivate CR
S --> CTRL: Candidates
deactivate S
CTRL --> UI: Candidates
deactivate CTRL
UI --> CM: Display Candidates list and asks to choose one
CM->UI: Inputs index of candidate
UI -> CTRL: allApplicationsById (candidates.get ( index ) )
activate CTRL
CTRL -> P: repositories()
activate P
P --> CTRL: repositories
deactivate P
CTRL -> RF: jobOpeningApplicationRepository()
activate RF
RF --> CTRL: jobOpeningApplicationRepository
deactivate RF
CTRL -> JAR: allApplicationsByIdWithInterview(candidates.get ( index ))
activate JAR
JAR --> CTRL: JobOpeningApplications
deactivate JAR
CTRL --> UI: JobOpeningApplications
deactivate CTRL




UI--> CM : Show all job applications of the selected candidate
CM->UI : Selects a application
UI-->CM: Requests the path of the file that's being uploaded
CM->UI: Provides the path of the file
UI->CTRL : uploadInterviewAnswersFile (application, filePath)
activate CTRL
CTRL->APPS: uploadInterviewAnswersFile (application, filePath)
activate APPS
APPS->Aps:setInterviewAnswersFile(filePath)
activate Aps
Aps-->APPS: updatedInterviewAnswersFile
deactivate Aps
APPS-->CTRL: updatedInterviewAnswersFile
deactivate APPS
CTRL-->UI: updatedInterviewAnswersFile
deactivate CTRL
UI-->CM : Confirmation that the file has been properly updated
deactivate UI

deactivate CM

@enduml
