@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) -  Notify candidates by email

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : Notify candidates by email
activate System

System --> Agent: Show list of possible notified candidates
deactivate

Agent -> System : Select one candidates to be notified
activate System

System --> Agent : Sent email



deactivate Agent

@enduml