@startuml

rectangle application{
    class JobOpeningApplication<<Aggregate Root>><<Entity>>{}


rectangle interview{
    class Interview<<Aggregate Root>><<Entity>>{}

}

    class Candidate<<Aggregate Root>><<Entity>>{}

}

rectangle Server{
    class Server<<Aggregate Root>><<Entity>>{}

}

Candidate "1" <-- "1.."Server
JobOpeningApplication"1" o--> "1"Interview





@enduml