@startuml
'https://plantuml.com/use-case-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

participant "FollowupServer" as FS
participant "Server" as S
participant "EmailThread" as ET
participant "EmailSender" as ES
participant "EmailService" as ESvc


activate FS
FS -> S: Server(portNumber)
activate S
S --> FS: Server
deactivate S
FS -> ET: EmailThread()
activate ET
ET --> FS: EmailThread
ET -> ESvc: EmailService()
activate ESvc
ESvc --> ET: EmailService
deactivate ESvc
ET -> ES: EmailSender()
activate ES
ES --> ET: EmailSender
deactivate ES
FS -> ET: start()
ET -> ESvc: findBySend(false)
activate ESvc
ESvc --> ET: listOfEmails
deactivate ESvc
ET -> ESvc: setSendTrue(email)
activate ESvc
deactivate ESvc
ET -> ES: sendEmail(email.email(), email.text())
activate ES
loop for each email to be sent in the listOfEmails
ES --> ET: success message
end
deactivate ES
ET --> FS: success message
deactivate ET
deactivate FS

note right of FS
  This sequence diagram only represents the system's behavior
   when the follow-up server is started and the emails are sent,
    the way of obtaining the data is shown on user story 1015 sequence diagram
end note


@enduml