@startuml
'https://plantuml.com/class-diagram

hide methods





rectangle candidate #aabbcc{
    class Candidate<<Aggregate Root>><<Entity>>{}
    class CandidateId<<Identity>><<Value Object>>{}
    class CurriculumVitae<<Value Object>>{}
}




rectangle "PlugIn" #bababa {
    class Plugin <<Aggregate Root>><<Entity>>{}
    class PluginType<<Value Object>>{}
    class PluginId<<Identity>><<Value Object>>{}
    class PluginDescription<<Value Object>>{}
    class JarFile<<Value Object>>{}
    class Requirement<<Resource>>{}
    class InterviewModel<<Resource>>{}
}

Plugin "1" --> "1" PluginType
Plugin "1" -right-> "1" PluginId
Plugin "1" --> "1" PluginDescription
Plugin "1" --> "1" JarFile







Candidate "1"--> "1" CandidateId
Candidate "1"--> "1" CurriculumVitae






@enduml