@startuml

rectangle application{
    class JobOpeningApplication<<Aggregate Root>><<Entity>>{}


rectangle interview{
    class Interview<<Aggregate Root>><<Entity>>{}

}



JobOpeningApplication"1" o--> "1"Interview





@enduml