
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Publish job opening results

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System : Asks to rank candidates for a job opening
    activate System

    System --> User : Asks to select a job opening
    deactivate System

    User -> System: Selects a job opening
    activate System

    System --> User : Publishes results and displays operation success
    deactivate System

@enduml