@startuml

rectangle application{
    class JobOpeningApplication<<Aggregate Root>><<Entity>>{}




rectangle candidate{
    class Candidate<<Aggregate Root>><<Entity>>{}

}
JobOpeningApplication"1" o--> "1"Candidate






@enduml