@startuml

actor User
participant listJobOpeningsUI
participant listJobOpeningsController
participant JobOpeningsRepository

activate User
User -> listJobOpeningsUI : asks to list job openings
activate listJobOpeningsUI
listJobOpeningsUI -> listJobOpeningsController : requests list job openings
activate listJobOpeningsController
listJobOpeningsController -> JobOpeningsRepository : getjobOpenings()
activate JobOpeningsRepository
JobOpeningsRepository --> listJobOpeningsController : list of job openings
deactivate JobOpeningsRepository
listJobOpeningsController --> listJobOpeningsUI : returns list of job openings
deactivate listJobOpeningsController
listJobOpeningsUI --> User : shows list of job openings
deactivate listJobOpeningsUI

@enduml