@startuml

title Register Job Opening - Sequence Diagram

autonumber
actor "Customer Manager" as M
participant ListJobOpeningUI  as UI <<UI>>
participant ListJobOpeningController as Controller <<Application>>
participant JobOpeningService as JService <<Service>>
participant FilteringStrategy as FS <<Strategy>>
participant JobOpeningRepository as JRepo <<Persistence>>

activate M
activate UI

M -> UI : requests to list job openings

UI -> Controller : filteringStrategies()

activate Controller

Controller --> UI : returns filtering strategies

deactivate Controller

UI --> M :  asks to select the filtering strategy (No filter, by Description, by Date and by Code)

M -> UI : selects strategy

UI -> Controller : filteringStrategy(strategyIndex)

activate Controller

Controller --> UI : strategy

deactivate Controller

UI -> Controller : newCriteria(strategy)

activate Controller

Controller -> FS : newCriteria()

activate FS

FS --> Controller : returns filtering criteria



deactivate FS

Controller --> UI : returns filtering criteria


deactivate Controller

UI --> M : asks to input the filtering criteria

M -> UI : submits the criteria

UI -> Controller : listFilteredJobOpenings(strategy, criteria)

activate Controller

Controller -> JService : listFilteredJobOpenings(strategy, criteria)

activate JService

JService -> JRepo : findAll()

activate JRepo

JRepo --> JService : list of job openings

deactivate JRepo

JService --> FS : filter(criteria, toFilter)

activate FS

FS --> JService : list of job openings filtered

deactivate FS


JService --> Controller : list of job openings filtered

deactivate JService



deactivate JRepo

Controller --> UI : list of job openings filtered

deactivate Controller

UI --> M : Displays the list of job openings filtered




@enduml








