@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - List job openings

autonumber

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : request to list job openings

activate System

    System --> Agent : asks to input the name or code of the Job Opening

deactivate System


Agent -> System : submits the name or code

activate System

System --> Agent : asks to input the start date

deactivate System

Agent -> System : submits the start date

activate System

System --> Agent : asks to input the end date


deactivate System

Agent -> System : submits the end date

activate System





 System --> Agent : Displays the list of job openings filtered
deactivate System

deactivate Agent

@enduml