@startuml

title Register Job Opening - Sequence Diagram

autonumber
actor "Customer Manager" as M
participant AddJobOpeningUI  as UI <<UI>>
participant AddJobOpeningController as Controller <<Application>>
participant JobOpeningBuilder as JB <<Domain>>
participant JobOpening as JO <<Domain>>
database JobOpeningRepository as JRepo <<Persistence>>

activate M
activate UI

M -> UI : requests to list job openings

UI --> M : asks to input the name or code of the Job Opening

M -> UI : submits the name or code

UI --> Controller : requests to register job opening

activate Controller

Controller -> JB: withJobOpeningCode(code)
activate JB
Controller -> JB: withJobOpeningName(name)
Controller -> JB: withJobOpeningDescription(description)
Controller -> JB: build()


deactivate JRepo
JB -> JO: create
JB --> Controller: returns job opening
deactivate JB



Controller -> JRepo: save(jobOpening)
activate JRepo

JRepo --> Controller: returns success
deactivate JRepo
Controller --> UI: returns success
deactivate Controller

UI --> M: confirms successful registration

@enduml








