@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - List job openings

autonumber

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : Request to list job openings

opt If user pretends to filter by date interval
activate System

    System --> Agent : Asks to input the date interval of the filtering

Agent -> System : Submits the interval

activate System
end
opt If the user chooses to filter by customer name or code
System --> Agent : Asks to input the customer name or code for filtering (optional)
deactivate System

Agent -> System : Submits the customer name or code (if applicable)

activate System
end

 System --> Agent : Displays the list of job openings sorted by the selected algorithm

deactivate System

deactivate Agent

@enduml