@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - List job openings

autonumber

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : request to list job openings

activate System

    System --> Agent : asks to select the filtering strategy (No filter, by Description, by Date and by Code)

deactivate System


Agent -> System : selects strategy

activate System

    System --> Agent : asks to input the filtering criteria

deactivate System

Agent -> System : submits the criteria

activate System

 System --> Agent : Displays the list of job openings filtered
deactivate System

deactivate Agent

@enduml