@startuml
'https://plantuml.com/class-diagram

hide methods


rectangle "Job Opening Application" #aaccbb {
    class Application<<Aggregate Root>><<Entity>>{}
    class ApplicationId<<Identity>><<Value Object>>{}
    class AttachedEmail<<Value Object>>{}
    class AttachedFile<<Value Object>>{}
    class ApplicatorData<<Value Object>>{}
    class ApplicationStatus<<Value Object>>{}
    class ApplicationGrade<<Value Object>>{}
}


rectangle candidate #aabbcc{
    class Candidate<<Aggregate Root>><<Entity>>{}
    class CandidateId<<Identity>><<Value Object>>{}
    class CurriculumVitae<<Value Object>>{}
}





  rectangle "Job Opening Interview" #ccbbaa {
      class JobInterview <<Aggregate Root>><<Entity>>{}
      class JobInterviewId<<Identity>><<Value Object>>{}
      class InterviewDate<<Value Object>>{}
      class InterviewTime<<Value Object>>{}
      class Score<<Value Object>>{}
      class InterviewResult<<Value Object>>{}
  }





Candidate "1"--> "1" CandidateId
Candidate "1"--> "1" CurriculumVitae


Application "1" --> "1" ApplicationId
Application "1" --> "1" AttachedEmail
Application "1" --> "1" AttachedFile
Application "1" --> "1" ApplicatorData
Application "1" -> "1" Candidate : submitted by
Application "1" --> "1" ApplicationStatus
Application "1" --> "1" ApplicationGrade

JobInterview "1" -up-> "1" JobInterviewId
JobInterview "1" -up-> "1" InterviewDate
JobInterview "1" --> "1" InterviewTime
JobInterview "1" -> "1" Score
JobInterview "1" --> "1" InterviewResult

JobInterview "1" -> "1" Candidate : with


@enduml