@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - Grade Interviews for a Job Opening

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : evaluate the grade for an interview
activate System

System --> Agent: select the list of job Interviews with answers
deactivate

Agent -> System : select the job interview
activate System

System --> Agent : Show the score for the jobinterview



@enduml