@startuml
'https://plantuml.com/class-diagram

hide methods

rectangle "Job Opening Interview" #ccbbaa {
    class JobInterview <<Aggregate Root>><<Entity>>{}
    class JobInterviewId<<Identity>><<Value Object>>{}
    class InterviewDate<<Value Object>>{}
    class InterviewTime<<Value Object>>{}
    class Score<<Value Object>>{}
    class InterviewResult<<Value Object>>{}
}

rectangle "PlugIn" #bababa {
    class Plugin <<Aggregate Root>><<Entity>>{}
    class PluginType<<Value Object>>{}
    class PluginId<<Identity>><<Value Object>>{}
    class PluginDescription<<Value Object>>{}
    class JarFile<<Value Object>>{}
    class Requirement<<Resource>>{}
    class InterviewModel<<Resource>>{}
}

JobInterview "1" -up-> "1" JobInterviewId
JobInterview "1" -up-> "1" InterviewDate
JobInterview "1" --> "1" InterviewTime
JobInterview "1" --> "0..1" Score
JobInterview "1" --> "1" InterviewResult

JobInterview "1" --> "1..*" "Plugin"

Plugin "1" --> "1" PluginType
Plugin "1" -right-> "1" PluginId
Plugin "1" --> "1" PluginDescription
Plugin "1" --> "1" JarFile


@enduml