@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - Grade Interviews for a Job Opening

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : evaluate the grade for an interview
activate System

System --> Agent: request the path for the interview
deactivate

Agent -> System : Type the path
activate System

System --> Agent : Show the score



@enduml