@startuml

title Enable Candidate - Sequence Diagram

autonumber
actor Operator as ADM
participant "EnableCandidateUI" as UI <<ui>>
participant ":EnableCandidateController" as CTRL <<application>>
participant "ListCandidatesUI" as LUI <<ui>>
participant "Candidate" as EU <<domain>>
participant "CandidateRepository" as REPO <<repository>>
participant "SystemUser" as SYS <<domain>>

activate ADM
ADM-> UI : Request to enable a candidate
activate UI
UI -> CTRL : create(userRepo)
UI -> LUI: listDisabledCandidates()
activate LUI
LUI --> UI : list
deactivate LUI
UI-->ADM: returns a list of the disabled candidates
deactivate UI
ADM -> UI : selects a disabled candidate
activate UI
UI -> CTRL : enableCandidate(email)
activate CTRL
CTRL-> SYS: .user()
activate SYS
SYS -> SYS : .activate()
CTRL -> REPO : save(candidate)
activate REPO
deactivate SYS
deactivate REPO
CTRL --> UI : returns success
deactivate CTRL
UI --> ADM : displays success
deactivate UI


@enduml
