@startuml




package ui {
        class AddCandidateUI {
        }
    }




    package application {
        class AddCandidateController {
            +addCandidate()
        }
    }

    package repository {

        interface CandidateRepository{
        }
    }

    package domain {
        class Role {}

        class AuthorizationService {
            +authorizationService() : AuthorizationService
            +ensureAuthenticatedUserHasAnyOf()
        }

        class CandidateManagementService {
            +candidateService() : CandidateManagementService
            +registerNewCandidate()
        }

        class SystemCandidateBuilder {
            +with() : SystemCandidateBuilder
            +build(): Candidate
        }

        class Candidate {
        }
    }



CandidateManagementService --> CandidateRepository
CandidateManagementService --> SystemCandidateBuilder
AddCandidateUI --> AddCandidateController
AddCandidateController --> CandidateManagementService
AddCandidateController --> SystemCandidateBuilder
AddCandidateController --> CandidateRepository
AddCandidateController --> AuthorizationService
CandidateRepository -> Candidate

@enduml