@startuml

left to right direction
title US1000 - Jobs4UUser Management Use Cases
skinparam titleBorderRoundCorner 20
skinparam titleBorderThickness 2
skinparam arrowThickness 3

'**********Manager Use cases*************
:Administrator: as ADM

Usecase MU01 as "Register a User"
Usecase MU02 as "Enable a User"
Usecase MU03 as "Disable a User"
Usecase MU04 as "List all the Users"

ADM -d- MU01
ADM -d- MU02
ADM -d- MU03
ADM -d- MU04


@enduml