@startuml
actor "Customer Manager" as u
participant ":RequirementsVerificationProcessUI" as ui <<UI>>
participant ":RequirementsVerificationProcessController" as controller <<Application>>
participant ":RequirementsVerificationProcessService" as service <<Service>>
participant ":JobApplicationRepository" as repository <<Repository>>
participant ":JobOpeningApplication" as application <<Entity>>

activate u
u -> ui: Requests to execute the process of verification of requirements of applications
activate ui
ui -> controller: executeVerificationProcess()
activate controller
controller -> service: executeVerificationProcess()
activate service
service -> repository: findAll()
activate repository
repository --> service: List<JobApplication> applications
deactivate repository
service -> service: filterApplications(applications)
loop applications
activate service
    service -> service: verifyRequirements(application)
    service -> application: updateStatus()
    activate application
    application --> service: JobOpeningApplication
    deactivate application
    service -> repository: save(application)
    activate repository
    repository --> service: JobOpeningApplication
    deactivate repository
    deactivate service

end

service --> controller: applications
deactivate service
controller --> ui: applications
deactivate controller

ui --> u: Displays all applications with the status(ACCEPTED/REJECTED) of requirements verification
deactivate ui
@enduml