@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) -  Execute the process of verification of requirements of applications

actor "Customer Manager" as u
participant ":System" as s

activate u
u -> s: Requests to execute the process of verification of requirements of applications
activate s
s --> u: Displays all applications with the status(ACCEPTED/REJECTED) of requirements verification



deactivate s

@enduml