@startuml

skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

top to bottom direction

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FF99
    ArrowColor grey
    BorderColor black
}

skinparam card {
    LifeLineBorderColor Green
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFDD
    ArrowColor DarkGrey
    BorderColor Black
}


hide methods

title Domain Model

class JobOpening <<Root Entity>>

class Phase <<Root Entity>>

class PhaseData <<Value Object>>

JobOpening "1" --> "4..5" Phase
Phase "1" --> "1" PhaseData


@enduml