@startuml
'https://plantuml.com/class-diagram

hide methods
skinparam linetype ortho



rectangle candidate #aabbcc{
    class Candidate<<Aggregate Root>><<Entity>>{}
    class CandidateId<<Identity>><<Value Object>>{
'        -id : Long
    }

    class CandidateAddress<<Value Object>>{
'        - address : String
    }
}


rectangle customer #bbaacc{
    class Customer <<Aggregate Root>><<Entity>>{
    }
    class CustomerId<<Identity>><<Value Object>>{
'        - id : Long
    }
}


rectangle sharedObjects {

    class Email <<Value Object>>
    class PhoneNumber <<Value Object>>
    class Username <<Value Object>>
    class Address <<Value Object>>

}



rectangle "Job Opening" #bbccaa {

    class JobOpening<<Aggregate Root>><<Entity>>{

    }

    class JobReference<<Identity>><<Value Object>>{
'        - sequenceId : id
'        - companyCode: String
    }

    class TitleOrFunction<<Value Object>>{
'        - epitaph : String
    }

    enum ContractType<<Enumerated>><<Value Object>>{
'        + FULL_TIME
'        + PART_TIME
    }

    class Mode<<Enumerated>><<Value Object>>{
'        + REMOTE
'        + HYBRID
'        + ON_SITE
    }


    class VacanciesNumber<<Value Object>>{
'        - numberOfVacancies : Integer
    }

    class Description<<Value Object>>{
'        - description : String
    }

    ''Maybe go to Interview Model
    class Requirements<<Value Object>>{
'        - title: String
'        - value : String
    }

}


rectangle "Job Opening Application" #aaccbb {

    class Application<<Aggregate Root>><<Entity>>{}

    class ApplicationId<<Identity>><<Value Object>>{
'        - id : Long
    }

    class AttachedEmail<<Value Object>>{
'        - text : String
    }

    class AttachedFile<<Value Object>>{
'        - orcText : String
'        - pathToFile: String
    }

    class ApplicatorData<<Value Object>>{

    }




}

rectangle "Job Opening Process" #ccbbcc{
    class JobOpeningProcess<<Aggregate Root>><<Entity>>{}
    class JobOpeningProcessId<<Identity>><<Value Object>>{
}

''rectangle interview #ccbbaa{


   '' class InterviewModel <<Aggregate Root>><<Entity>>{}

   '' class InterviewModelName<<Value Object>>{}

   '' abstract Question<<Entity>><<Prototype>>{}

   '' class TrueFalseQuestion<<Entity>> {}

   '' class ShortTextQuestion<<Entity>>  {}

   '' class SingleChoiceQuestion<<Entity>> {}

   '' class MultipleChoiceQuestion<<Entity>> {}

   '' class IntegerQuestion<<Entity>> {}

   '' class RealNumberQuestion<<Entity>> {}

   '' class DateQuestion<<Entity>> {}

   '' class TimeQuestion<<Entity>> {}

   '' class ScaleQuestion<<Entity>> {}

''}


JobOpening "1" -up-> "1" JobReference
JobOpening "1" -up-> "1" TitleOrFunction
JobOpening "1" --up-> "1" ContractType
JobOpening "1" -left-> "1" Mode
JobOpening "1" ---> "1" VacanciesNumber
JobOpening "1" --> "1" Description
JobOpening "1" ---> "1" Requirements
JobOpening "*" --> "1" Customer : set by

Candidate "1" --> "1" CandidateId
Candidate "1" --> "1" CandidateAddress


Application "1" --> "1" ApplicationId
Application "1" --> "1" AttachedEmail
Application "1" --> "1" AttachedFile
Application "1" --> "1" ApplicatorData
Application "*" -----> "1" JobOpening : submitted for
Application "*" -> "1" Candidate : submitted by


Customer "1" --> "1" CustomerId


JobOpeningProcess "1" --> "1" JobOpeningProcessId
JobOpening "1" -----> "*" JobOpeningProcess : has


''InterviewModel "1" -left-> "1" InterviewModelName : has
''InterviewModel "1" -down--> "*" Question : contains
''Question <|-- InterviewModel : belongs to


Candidate "1" --> "1" Username
Candidate "1" --> "1" PhoneNumber
Candidate "1" --> "1" Email


Customer "1" --> "1" Username
Customer "1" --> "1" PhoneNumber
Candidate "1" --> "1" Email

''RealNumberQuestion -up-|> Question
''ScaleQuestion -up-|> Question
''SingleChoiceQuestion --|> Question
''IntegerQuestion -up-|> Question
''TimeQuestion --|> Question
''ShortTextQuestion -left-|> Question
''TrueFalseQuestion --|> Question
''MultipleChoiceQuestion -up-|> Question
''DateQuestion --|> Question


Customer "1" --> "*" Address
JobOpening "1" --> "*" Address

@enduml