@startuml
'https://plantuml.com/class-diagram

hide methods
skinparam linetype ortho



rectangle candidate #aabbcc{
    class Candidate<<Aggregate Root>><<Entity>>{}
    class CandidateId<<Identity>><<Value Object>>{}
}


rectangle customer #bbaacc{
    class Customer <<Aggregate Root>><<Entity>>{}
    class CustomerId<<Identity>><<Value Object>>{}
}


rectangle "Shared Objects" {

    class Email <<Value Object>>
    class PhoneNumber <<Value Object>>
    class Username <<Value Object>>
    class Address <<Value Object>>

}



rectangle "Job Opening" #bbccaa {

    class JobOpening<<Aggregate Root>><<Entity>>{}

    class JobReference<<Identity>><<Value Object>>{}

    class TitleOrFunction<<Value Object>>{}

    enum ContractType<<Enumerated>><<Value Object>>{}

    class Mode<<Enumerated>><<Value Object>>{}


    class VacanciesNumber<<Value Object>>{}

    class Description<<Value Object>>{}

    ''Maybe go to Interview Model

}


rectangle "Job Opening Application" #aaccbb {

    class Application<<Aggregate Root>><<Entity>>{}

    class ApplicationId<<Identity>><<Value Object>>{}

    class AttachedEmail<<Value Object>>{}

    class AttachedFile<<Value Object>>{}

    class ApplicatorData<<Value Object>>{}

    class ApplicationStatus<<Value Object>>{}




}

rectangle "Job Opening Process" #ccbbcc{
    class JobOpeningProcess<<Aggregate Root>><<Entity>>{}
    class JobOpeningProcessId<<Identity>><<Value Object>>{}
    class JobOpeningProcessStatus<<Value Object>>{}
    class JobOpeningProcessStage<<Value Object>>{}
    class Phase<<Value Object>>{
        }
    enum PhaseType<<Enumerated>><<Value Object>>{
        APPLICATION
        SCREENING
        INTERVIEWS
        ANALYSIS
        RESULT
    }
}

rectangle "Job Opening Interview" #ccbbaa {
    class JobInterview <<Aggregate Root>><<Entity>>{}
    class JobInterviewId<<Identity>><<Value Object>>{}
    class InterviewDate<<Value Object>>{}
    class InterviewTime<<Value Object>>{}
    class Score<<Value Object>>{}
    class InterviewResult<<Value Object>>{}
}



rectangle "Interview Model" #accbcc {

}

rectangle "Requirements" #cbcbac {

}

rectangle "PlugIn" #bababa {
    class Plugin <<Aggregate Root>><<Entity>>{}
    class PluginType<<Value Object>>{}
    class PluginId<<Identity>><<Value Object>>{}
    class PluginDescription<<Value Object>>{}
    class JarFile<<Value Object>>{}
}



Plugin "1" --> "1" PluginType
Plugin "1" -right-> "1" PluginId
Plugin "1" --> "1" PluginDescription
Plugin "1" --> "1" JarFile


JobOpening "1" -up-> "1" JobReference
JobOpening "1" -up-> "1" TitleOrFunction
JobOpening "1" --up-> "1" ContractType
JobOpening "1" -left-> "1" Mode
JobOpening "1" ---> "1" VacanciesNumber
JobOpening "1" --> "1" Description
JobOpening "1" ---> "1" Requirements
JobOpening "*" --> "1" Customer : set by
JobOpening "*" --> "1" Requirements


Candidate "1" --> "1" CandidateId


Application "1" --> "1" ApplicationId
Application "1" --> "1" AttachedEmail
Application "1" --> "1" AttachedFile
Application "1" --> "1" ApplicatorData
Application "*" -----> "1" JobOpening : submitted for
Application "*" -> "1" Candidate : submitted by
Application "1" --> "1" ApplicationStatus

Customer "1" --> "1" CustomerId


JobOpeningProcess "1" -left-> "1" JobOpeningProcessId
JobOpening "1" -----> "*" JobOpeningProcess : has
Phase "1" --> "1" JobOpeningProcessStatus
Phase "1" --> "1" JobOpeningProcessStage
JobOpeningProcess "1" --> "1" Phase

Phase "*" -down-> "1" PhaseType


''InterviewModel "1" -left-> "1" InterviewModelName : has
''InterviewModel "1" -down--> "*" Question : contains
''Question <|-- InterviewModel : belongs to


Candidate "1" --> "1" Username
Candidate "1" --> "1" PhoneNumber
Candidate "1" --> "1" Email


Customer "1" --> "1" Username
Customer "1" --> "1" PhoneNumber
Candidate "1" --> "1" Email


Customer "1" --> "*" Address
JobOpening "1" --> "*" Address


JobInterview "1" -up-> "1" JobInterviewId
JobInterview "1" -up-> "1" InterviewDate
JobInterview "1" --> "1" InterviewTime
JobInterview "1" -> "1" Score
JobInterview "1" --> "1" InterviewResult

Requirements  -right-|> Plugin
"Interview Model" --|> Plugin
JobOpening "*" --> "1" "Interview Model"


Application "1" -up-> "1" JobInterview


@enduml