@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register a customer

autonumber

actor "Customer Manager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : requests to register a customer
    activate System

    System --> Manager : show information about the customer (username, password, email, firstName, lastName, role).

    deactivate System

    Manager -> System : provides the information

    activate System


        System --> Manager : shows and requests confirmation for the customer registration
        deactivate System

        Manager -> System : confirms registration
        activate System

        System --> Manager : confirms successful registration

@enduml