@startuml

package UI{
    class AddCustomerUI{
    +doShow()
    +headLine()
    }
}

package Controller{
    class AddCustomerController{
    +addCustomer()

    }
}

package Domain{


    class UserManagementService{
    +registerNewUser()
    }



    class Customer{
    -username
    -firstName
    -lastName
    -email
    -password
    -role
    +create()
    }

    class RegisterNewUser<<Event>>{
    }


}

package Repository{
    class UserRepository{
    +save()
    }
}

AddCustomerUI ..> AddCustomerController

AddCustomerController ..> UserManagementService

RegisterNewUser --> Customer: creates
UserManagementService --> UserRepository: uses
AddCustomerController --> RegisterNewUser: creates

@enduml