@startuml

interface ClientUser {

}

class Customer <<Root>>{
    -email
    -username
    -firstName
    -lastName
    -password
    -role
}

class Student <<Root>>{
    -Customer
    -birthDate
    -taxPayerNumber
    -mechanographicNumber
}

class MechanographicNumber <<Value Object>>{
    -mechanographicNumber
    -validMechanographic(mechanographicNumber)
}



class Acronym <<Value Object>>{
    -acronym
    -validAcronym(acronym)
}

class Email <<Value Object>>{
    -email
    -validEmail(email)
}

class TaxPayerNumber <<Value Object>>{
    -taxPayerNumber
    -validTaxPayerNumber(taxPayerNumber)
}

ClientUser <|.. Student
Student *-- TaxPayerNumber
Customer *-- Email
Student "1" *-- "1" MechanographicNumber

note "Only Customer with \nManager Role can manage \nother Customers" as N_Man

Customer "*" -- "*" Customer : manages >
Customer --o Student

@enduml