@startuml

title Register Customer - Sequence Diagram

autonumber
actor "Customer Manager" as M
participant AddCustomerUI as UI <<UI>>
participant AddCustomerController as Controller <<Application>>
participant UserManagementService as MN <<Domain>>
participant JobOpening as JO <<Domain>>
database UserRepository as UserRepo <<Persistence>>

activate M
M -> UI : onLoad
activate UI
UI -> Controller: addCustomer()
activate Controller
Controller -> MN: registerNewUser()

activate MN
MN -> UserRepo: registerNewUser()
activate UserRepo

UserRepo --> MN: returns customer
deactivate UserRepo
MN -> JO: create
MN --> Controller: returns customer
deactivate MN




Controller -> UserRepo: save(customer)
activate UserRepo

UserRepo --> Controller: returns success
deactivate UserRepo
Controller --> UI: returns success
deactivate Controller

UI --> M: confirms successful registration

@enduml