@startuml

title Register Job Opening - Sequence Diagram

autonumber
actor "Customer Manager" as M
participant RegisterJobOpeningUI as UI <<UI>>
participant RegisterJobOpeningController as Controller <<Application>>
participant JobOpeningBuilder as JB <<Domain>>
participant JobOpening as JO <<Domain>>
database JobOpeningRepository as JRepo <<Persistence>>

activate M
activate UI

M -> UI : requests to register a job opening

UI --> M :prompts for job details (name, code, description)

M -> UI : provides job details

UI --> M : shows and requests confirmation for job registration

M -> UI : confirms job registration

UI -> Controller: registerJobOpening(code, name, description)

activate Controller

Controller -> JB: withJobOpeningCode(code)
activate JB
Controller -> JB: withJobOpeningName(name)
Controller -> JB: withJobOpeningDescription(description)
Controller -> JB: build()

JB -> JRepo: ofIdentity(code)
activate JRepo

JRepo --> JB: returns job opening
deactivate JRepo
JB -> JO: create
JB --> Controller: returns job opening
deactivate JB



Controller -> JRepo: save(job opening)
activate JRepo

JRepo --> Controller: returns success
deactivate JRepo
Controller --> UI: returns success
deactivate Controller

UI --> M: confirms successful registration

@enduml