@startuml
Actor "Customer Manager" as User
participant ":UpdateJobOpeningUI" as UI <<UI>>
participant ":EditJobOpeningController" as Controller <<Application>>
participant ":JobOpeningService" as JobOpeningService <<Application>>

participant ":AuthorizationService" as Auth <<Application>>
participant ":UserSession" as UserSession <<Application>>
participant ":SystemUser" as SystemUser <<Domain>>
database "JobOpeningRepository" as jobrepo <<Repository>>
participant ":JobOpeningMapper" as JobOpeningMapper <<Domain>>


activate User

User -> UI: Chooses to edit a job opening
activate UI

UI -> Controller : Request to edit job opening
activate Controller

Controller -> Auth : ensureAuthenticatedUserHasAnyOf(BaseRoles.CUSTOMER_MANAGER, BaseRoles.ADMIN, BaseRoles.POWER_USER)
activate Auth

Auth --> Controller : User is authorized
deactivate Auth

Controller -> UserSession : getUser()
activate UserSession
UserSession -> SystemUser: user()
activate SystemUser
SystemUser --> UserSession: returns user
deactivate SystemUser
UserSession --> Controller: returns user
deactivate UserSession
deactivate Controller
loop while confirmation == false

UI -> User: asks for JobReference
User --> UI: enters JobReference

UI -> Controller : validateJobReference(jobReference)
activate Controller
Controller -> JobOpeningService: verifyJobReference(jobReference)
activate JobOpeningService
JobOpeningService -> jobrepo: findByJobReference(jobReference)
activate jobrepo
jobrepo --> JobOpeningService: jobOpening
deactivate jobrepo
JobOpeningService -> jobrepo: isCreatedByCurrentUser(jobOpening, user)
activate jobrepo
alt returns true
jobrepo --> JobOpeningService: return jobOpening

else returns false
jobrepo --> JobOpeningService: return null
deactivate jobrepo
end
alt jobOpening is null
JobOpeningService --> Controller: jobOpening is null
deactivate JobOpeningService
Controller --> UI: displayError("JobOpening not found")
deactivate Controller
UI --> User: displays error message
else jobOpening is not null
activate JobOpeningService
activate Controller
JobOpeningService --> Controller: jobOpening
deactivate JobOpeningService

Controller --> UI: displayJobOpening(jobOpening)
deactivate Controller
UI --> User: displays jobOpening
end
UI -> User: request confirmation
deactivate UI
User -> UI: inputs confirmation
activate UI
end
UI -> Controller: displayEditingOptions()
activate Controller

Controller -> UI : updateList(Edit.values())
deactivate Controller
loop until user chooses to stop
UI -> User : displays parameters to edit and option to stop
User --> UI : Chooses parameter to edit
UI -> UI: return list add(option)
end
UI --> Controller : returns List <Edit> edits
activate Controller

Controller -> JobOpeningService : toDto(jobOpening)
activate JobOpeningService

 JobOpeningService -> JobOpeningMapper: toDto(jobOpening)
 activate JobOpeningMapper

 JobOpeningMapper --> JobOpeningService: jobOpeningDto
 deactivate JobOpeningMapper

 JobOpeningService --> Controller: jobOpeningDto
  deactivate JobOpeningService

loop for each edit

alt edit is a string
Controller -> UI : updateString(Edit.StringField)
UI -> User : request to update string field
User --> UI : enters new value
UI --> Controller : returns new value
end

alt edit is a number
Controller -> UI : updateNumber(Edit.NumberField)
UI -> User : request to update string field
User --> UI : enters new value
UI --> Controller : returns new value
end

alt edit is a Enum
Controller -> UI : updateEnum(Edit.EnumField)
UI -> User : request to update string field
User --> UI : enters new value
UI --> Controller : returns new value
end

Controller -> JobOpeningService : updateJobOpening(jobOpeningDto, edit, value)
activate JobOpeningService

JobOpeningService --> Controller : returns jobOpeningDto
deactivate JobOpeningService
end

Controller --> UI : displayJobOpening(jobOpeningDTO)

UI -> User : displays updated jobOpening

Controller -> JobOpeningService : toDomain(jobOpeningDto)
activate JobOpeningService

JobOpeningService -> JobOpeningMapper: toDomain(jobOpeningDto)
activate JobOpeningMapper

 JobOpeningMapper --> JobOpeningService: jobOpening
deactivate JobOpeningMapper

 JobOpeningService -> jobrepo: save(jobOpening)
 activate jobrepo
 jobrepo --> JobOpeningService: saved jobOpening
deactivate jobrepo
JobOpeningService --> Controller: returns true
deactivate JobOpeningService
Controller --> UI : returns true
deactivate Controller
UI --> User : displays success message
deactivate UI
@enduml