@startuml

Actor "Customer Manager" as U
Participant "System" as S

activate U

U -> S: selects option to edit a job opening
activate S
S -> U : list all Job References and asks user to choose a job opening
U -> S : chooses a job opening
S -> U : shows Job Opening details
loop until user chooses to stop
S -> U : Asks to choose what user wants to update
S -> S: Saves options to update
end
loop for every single choice
S -> U : Asks for new value
U -> S : Enters new value
end
S -> U : Shows updated Job Opening details with confirmation message

@enduml