@startuml
'https://plantuml.com/class-diagram

package authz
{
    class DeactivateUserUI {
        #doShow() : boolean
        +headLine() : String
    }
}

package Appplication {
    class DeactivateUserController {
        +deactivateUser(final SysteUser user) : SystemUser
        +activeUsers() : Iterable<SystemUser>
    }
}

package Libraries{
    class UserManagementService
    class AuthorizationService
    class LoggerFactory
    class AuthzRegistry
}

DeactivateUserUI --.> DeactivateUserController
DeactivateUserController --.> UserManagementService
DeactivateUserController --.> AuthorizationService
DeactivateUserController -.-> LoggerFactory
DeactivateUserController -.-> AuthzRegistry




@enduml