@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register job opening

autonumber

actor "Customer Manager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : requests to register a job opening
    activate System

    System --> Manager : prompts for job details (name, code, description)
    deactivate System

    Manager -> System : provides job details

    activate System


        System --> Manager : shows and requests confirmation for job registration
        deactivate System

        Manager -> System : confirms job registration
        activate System

        System --> Manager : confirms successful registration

@enduml