@startuml

left to right direction
'
'
'package ui {
'        class RegisterJobOpeningUI {
'        }
'    }
'
'package coursemanagement {
'
'
'    package application {
'        class RegisterJobOpeningController {
'            +registerJobOpening()
'        }
'    }
'
'    package repository {
'        interface JobOpeningRepository {
'            +ofIdentity(): JobOpening
'        }
'    }
'
'    package domain {
'        class JobOpening {}
'
'        class JobOpeningCode {}
'
'        class JobOpeningName {}
'
'        class JobOpeningDescription {}
'
'        enum JobOpeningState {}
'
'        class JobOpeningBuilder {
'            +withJobOpeningCode(): JobOpeningBuilder
'            +withJobOpeningName(): JobOpeningBuilder
'            +withJobOpeningDescription(): JobOpeningBuilder
'            +build(): JobOpening
'        }
'    }
'
'
'}
'
'JobOpening --> JobOpeningCode
'JobOpening --> JobOpeningDescription
'JobOpening --> JobOpeningName
'JobOpening --> JobOpeningState
'JobOpeningBuilder --> JobOpening
'JobOpeningBuilder --> JobOpeningRepository
'
'RegisterJobOpeningUI --> RegisterJobOpeningController
'RegisterJobOpeningController --> JobOpeningRepository
'RegisterJobOpeningController --> JobOpeningBuilder
'JobOpeningRepository -> JobOpening

@enduml