@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) -  Display all the data of an application

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : asks to list job opening applications
activate System

System --> Agent: show list of job references and asks to select one
deactivate

Agent -> System : selects job reference
activate System

System --> Agent : show list of applications
System --> Agent : asks if the user wants to see all data from one of the applications
deactivate

alt if the user wants to see all data from one of the applications

Agent -> System : selects an application
activate System

System --> Agent : display Candidate data and returns to Customer Manager Menu

else
System --> Agent :returns the Customer Manager Menu

end


deactivate Agent

@enduml
