@startuml

title US 1021 - Display all the data of an application

actor "Customer Manager" as User

participant ":ListJobOpeningApplicationsUI" as UI <<UI>>
participant ":ListJobOpeningApplicationsController" as Controller <<Controller>>
participant ":JobOpeningRepository" as Repository <<Persistence>>
participant ":ApplicationRepository" as ApplicationRepository <<Persistence>>



activate User

User -> UI: asks to list job opening applications

activate UI

UI -> Controller:AllJobOpenings()
    activate Controller

Controller -> Repository: AllJobOpenings()

    activate Repository

    Repository --> Controller: jobOpenings

    deactivate Repository

    Controller --> UI: jobOpenings

    deactivate Controller
    UI --> User: show list of job references and asks to select one
deactivate UI

User -> UI: selects job reference

activate UI

    UI -> Controller: AllApplicationsForJobOpening(jobOpening)

    activate Controller


Controller -> ApplicationRepository: AllApplicationsByJobOpening(jobOpening)
activate ApplicationRepository

ApplicationRepository --> Controller:  applications

deactivate ApplicationRepository
Controller --> UI: applications
deactivate Controller
UI --> User: show list of applications
UI --> User: asks if the user wants to see all data from one of the applications
alt if the user wants to see all data from one of the applications
User->UI: selects an application
UI -> Controller: application.get(index)
activate Controller
Controller --> UI: application
deactivate Controller
UI --> User: display Candidate data and returns to Customer Manager Menu


else

User <--UI: returns the Customer Manager Menu

end

deactivate UI

@enduml