@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) -  Display all the data of an application

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : asks to list job opening applications
activate System

System --> Agent: lists jobReferences and asks user to choose one
deactivate

Agent -> System : chooses job reference
activate System

System --> Agent : asks if the user wants to see all data from one of the applications
deactivate

alt
Agent -> System : respond affirmatively
activate System

System --> Agent : display Candidate data and returns to Customer Manager Menu
end


deactivate Agent

@enduml
