@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) - Rank Candidates for a Job Opening

actor "Customer Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : Request to rank candidates for a job opening
activate System
System --> Agent: Show list of applicable job openings
deactivate

Agent -> System : Select a job opening
activate System
System --> Agent : Show list of applications for the selected job opening
System --> Agent : Requests user to select one



loop while ranking all applications

System --> Agent : Requests new ranking
deactivate
Agent -> System : Provides new ranking
activate System
System --> Agent  : Confirms new ranking
deactivate System

end loop

deactivate Agent

@enduml