@startuml

skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

top to bottom direction

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FF99
    ArrowColor grey
    BorderColor black
}

skinparam card {
    LifeLineBorderColor Green
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFDD
    ArrowColor DarkGrey
    BorderColor Black
}


hide methods

title Domain Model



skinparam packageStyle rectangle



package "Client " {

class Client <<Root Entity>>
class ClientID <<Identifier>>

}

package "Job Offer" {

class PhaseData <<Value Object>>
class Phase <<Value Object>>
class JobOpeningRequirements <<Value Object>>
class InterviewDescription <<Value Object>>
class JobOpening <<Root Entity>>
class JobOpeningID <<Identifier>>
class Report <<Value Object>>
class Address <<Value Object>>
class Plugin <<Root Entity>>
class JarFile <<Value Object>>
class PluginDescription <<Value Object>>
class PluginID <<Identifier>>
class InterviewModel <<Value Object>>
class RequirementsSpecification <<Value Object>>

}

package "Job Offer Application" {

class Application <<Root Entity>>
class ApplicationID <<Identifier>>
class ApplicationStatus <<Value Object>>
class AnalyzedRequirements <<Value Object>>
class InterviewFeedback <<Value Object>>
class ReportFiles <<Value Object>>

}

package "Employees" {

class CustomerManager <<Root Entity>>
class CustomerManagerID <<Identifier>>
class Operator <<Root Entity>>
class OperatorID <<Identifier>>
class LanguageEngineer <<Root Entity>>
class LanguageEngineerID <<Identifier>>
class Company <<Value Object>>


}

package "Application Candidate" {

class Candidate <<Root Entity>>
class CandidateID <<Identifier>>

}



package "Administrator"{

class Admin <<Root Entity>>
class AdminID <<Identifier>>


}




CustomerManager "1" -- "*" Company


Company "1" -- "*" JobOpening

Client "1" -- "1" ClientID  : has >

ClientID "1" -- "*" JobOpening : submits >

JobOpening "1" --- "4..5" Phase :  >
JobOpening "0..1" -- "1" JobOpeningRequirements : composed by >
JobOpening "0..1" --- "0..1" InterviewDescription : has >
JobOpening "1" -- "1" Report : >
JobOpening "1" --- "1" Address : has >
JobOpening "1" -- "1" JobOpeningID : >

Phase "*" -- "1" PhaseData : has >

Report "1" -- "*" ReportFiles : originates >

Application "1" -- "1" InterviewFeedback : has >
Application "1" -- "1" AnalyzedRequirements : has >
Application "1" -- "1" ApplicationStatus : >
Application "1" -- "*" ReportFiles : >
ApplicationID "1" -- "1" Application : < has


CustomerManager "1" -- "1" CustomerManagerID : has >
LanguageEngineer "1" -- "1" LanguageEngineerID : has >





CandidateID "1" -- "*" Application : makes >
Candidate "1" -- "1" CandidateID : has >

Admin "1" -- "1" AdminID : has >
Admin "1" -- "*" CustomerManager : manage >

Operator "1" -- "1" OperatorID : has >
Admin "1" -- "*" Operator : manage >





Plugin "1" -- "1" PluginDescription : has >
Plugin "1" -- "1" JarFile : has >
Plugin "1" -- "1" PluginID : has >

Plugin <|-- InterviewModel : extends
Plugin <|-- RequirementsSpecification : extends

JobOpening "1" -- "1" InterviewModel : >
JobOpening "1" -- "1" RequirementsSpecification : >

LanguageEngineer "1" -- "1" Plugin : deploy >



'class Process {
'    description
'}

'class ContractType {
'}

'class Mode {
'

'class Company{
'}

'class Numberofvacancies{
'}

'class Requirements{
'}

@enduml