@startuml

title Register Student Sequence Diagram

autonumber
actor Administrator as ADM
participant "RegisterOperatorUI" as UI <<ui>>
participant "RegisterOperatorController" as CTRL <<application>>
participant "Jobs4UBuilderFactory" as FAC <<factory>>
participant "OperatorBuilder" as BLD <<builder>>
participant "SystemUser" as SU <<f_entity>>
participant "Jobs4UUser" as J4UU <<domain>>
database "Jobs4UUserRepository" as REPO <<repository>>


-> UI : onLoad
activate UI
UI -> CTRL : create(userRepo, userBuilderFactory)
UI --> ADM : asks input of\n language engineer details
ADM -> UI : inputs language engineer details
UI -> CTRL : registerLanguageEngineer(username, pwd,\n firstName, lastName, email)
activate CTRL
CTRL -> FAC : createJObs4UUserBuilder(role)
activate FAC
FAC -> BLD : create
FAC --> CTRL : builder
deactivate FAC
CTRL -> SU : create
CTRL -> BLD : withSystemUser(sysUser)
CTRL -> BLD : build()
activate BLD
BLD -> J4UU : create(sysUser)
BLD --> CTRL : user
deactivate BLD
CTRL -> REPO : save(user)
CTRL --> UI : returns success
deactivate CTRL
UI --> ADM : displays success





@enduml
