@startuml
title System Sequence Diagram (SSD) - Notification of Job Opening State Change

actor "Customer" as Customer
participant ":System" as System

activate Customer

Customer -> System : request to see the notifications

activate System

System --> Customer: displays the notification options (seen, unseen, all)

Customer -> System: selects one

System --> Customer: displays the notifications by the selected option

System --> Customer: displays operation sucess

@enduml