@startuml
title System Sequence Diagram - Being notified in my application when the state (phase) of job openings changes

actor Customer as Customer
participant System as "System"

activate Customer

Customer -> System: opens the Customer app
activate System

System --> Customer: types username
deactivate System

Customer -> System: types the username
activate System

System --> Customer: Requests password
deactivate System
Customer->System: types the password
activate System

System --> Customer: retrieves notifications
deactivate System

@enduml