
@startuml

title US 1005 - List Job Opening Applications

actor "User - Customer Manager" as User

participant "ListJobOpeningApplicationsUI" as UI <<UI>>
participant "ListJobOpeningApplicationsController" as Controller <<Controller>>
participant "JobOpeningRepository" as Repository <<Persistence>>
participant "ApplicationRepository" as ApplicationRepository <<Persistence>>



activate User

User -> UI: asks to list job opening applications

activate UI

UI -> Controller: new ListJobOpeningAplicationsController()
    activate Controller
UI -> Controller:AllJobOpenings()
Controller -> Repository: AllJobOpenings()

    activate Repository

    Repository --> Controller: Iterable<JobOpening> jobOpenings

    deactivate Repository

    Controller --> UI: jobOpenings

    deactivate Controller
    UI --> User: lists jobReferences and asks user to choose one
deactivate UI

User -> UI: chooses job reference

activate UI

    UI -> Controller: AllApplicationsForJobOpening(jobOpening)

    activate Controller


Controller -> ApplicationRepository: AllApplicationsByJobOpening(jobOpening)
activate ApplicationRepository

ApplicationRepository --> Controller:   Iterable<JobOpeningApplication> applications

deactivate ApplicationRepository
Controller --> UI: applications
deactivate Controller

UI --> User: printNumeratedList(applications)

UI --> User : Sens user back to Costumer Manager Menu

deactivate UI

@enduml