@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

title System Sequence Diagram (SSD) US3002 - list all my job openings

actor "Manager" as Agent
participant ":System" as System

activate Agent

Agent -> System : Enters the app
activate System

System --> Agent: requests username

Agent -> System : Enters username

System --> Agent : requests password


Agent -> System : Enters password


System --> Agent : Application
deactivate System


deactivate Agent

@enduml
