@startuml
title Sequence Diagram (US 2003 - Generate and export a template text file to help collect data fields for candidates of a job opening)

autonumber
actor Operator as Operator
participant GenerateTemplateUI as UI <<UI>>
participant GenerateTemplateController as CTRL <<Application>>
participant AuthorizationService as AS <<Domain>>
participant JobOpeningService as UMS <<Domain>>
database JobOpeningRepository as URepo <<Persistence>>



activate Operator
activate UI
Operator -> UI: Request to generate template file for job opening

UI -> CTRL**:create
activate CTRL
CTRL -> AS : authorizationService()
activate AS
AS --> CTRL: authz
deactivate AS
CTRL-> UMS : jobOpeningService()
activate UMS
UMS-->CTRL: jobOpeningService
deactivate CTRL
UMS-->UMS: getJobOpenings()
UMS-->CTRL : jobOpenings
deactivate UMS
activate CTRL
CTRL--> UI: jobOpenings
deactivate CTRL
UI --> Operator: Generating the template file
UI --> Operator: Template file ready for export
deactivate UI


@enduml