@startuml

title Register User Sequence Diagram - Starting point

autonumber
actor Administrator as ADM
participant "RegisterUserUI" as RUI <<ui>>
participant "RegisterUserController" as RUC <<application>>
participant "Jobs4URoles" as J4UR <<domain>>
participant "RegisterTypeUserUI" as RTUI <<ui>>

-> RUI : onLoad
activate RUI
RUI -> RUC : create
RUI -> RUC : existingRoles()
activate RUC
RUC -> J4UR : existingRoles()
activate J4UR
J4UR --> RUC : roles
deactivate J4UR
RUC --> RUI : roles
deactivate RUC
RUI -> ADM : displays\n available roles
ADM --> RUI : chooses role
RUI -> RUI: displayRoleUI()
activate RUI
RUI -> RTUI : create and display
activate RTUI
deactivate RUI
deactivate RUI



@enduml
