@startuml

actor CustomerManager as CM
participant UploadInterviewAnswersFileUI as UI <<UI>>
participant ListCandidatesController as CTRLList <<Application>>
participant CandidateManagementService as UMS <<Service>>
participant CandidateRepository as CRepo <<Persistence>>
participant UpdateInterviewAnswerController as CTRL <<Application>>
participant Candidate as CAN <<Domain>>
participant ApplicationService as APPS <<Service>>
participant ApplicationRepository AS APPRepo <<Persistence>>
participant Applications as Aps <<Domain>>




activate CM

CM -> UI: Requests to Upload Interview Answers File
activate UI


UI-> CTRLList: get all candidates from database
activate CTRLList
CTRLList-->CTRLList:allCandidates()
CTRLList-> UMS : allCandidate()
activate UMS
UMS->CRepo: findAllCandidates()
activate CRepo
CRepo --> UMS: all candidates
deactivate CRepo
UMS-->CTRLList: all candidates
deactivate UMS
CTRLList-->UI : all candidates
deactivate CTRLList
UI --> CM:Displays the candidates list

CM->UI : Select a candidate

UI -> CTRL: allApplicationsOfCandidate(candidate)
activate CTRL

CTRL -> CAN : identity()
activate CAN
CAN --> CTRL : identity
deactivate CAN

CTRL -> APPS : allApplicationsOfCandidate(identity)
activate APPS
APPS -> APPRepo: findApplicationByCandidateID(candidateID)
activate APPRepo
APPRepo--> APPS: allApplicationsOfCandidate
deactivate APPRepo

APPS-->CTRL : allApplicationsOfCandidate

deactivate APPS
CTRL-->UI:allApplicationsOfCandidate
deactivate CTRL
UI--> CM : Show all job applications of the selected candidate

CM->UI : Selects a application
UI-->CM: Requests the path of the file that's being uploaded
CM->UI: Provides the path of the file

UI->CTRL : uploadInterviewAnswersFile (application, filePath)
activate CTRL
CTRL->APPS: uploadInterviewAnswersFile (application, filePath)
activate APPS
APPS->Aps:setInterviewAnswersFile(filePath)
activate Aps
Aps-->APPS: updatedInterviewAnswersFile
deactivate Aps
APPS-->CTRL: updatedInterviewAnswersFile
deactivate APPS
CTRL-->UI: updatedInterviewAnswersFile
deactivate CTRL
UI-->CM : Confirmation that the file has been properly updated
deactivate UI

deactivate CM

@enduml
